# Generated by Django 6.0.6 on 2026-06-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_coursesubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="currency",
            field=models.CharField(default="rub", max_length=3, verbose_name="Валюта"),
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=1000, max_digits=10, verbose_name="Цена"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
